

export enum TransactionType {
  INCOME = 'INCOME',
  EXPENSE = 'EXPENSE',
  SAVINGS = 'SAVINGS'
}

export interface Transaction {
  id: string;
  amount: number;
  category: string;
  note: string;
  date: string;
  type: TransactionType;
  currency: string;
  excludeFromBalance?: boolean; 
}

export interface Goal {
  id: string;
  name: string;
  targetAmount: number;
  savedAmount: number;
  currency: string;
  category?: string;
  color?: string;
  isFixedDeposit?: boolean;
}

export interface Profile {
  id: string;
  name: string;
}

export interface DashboardStats {
  totalIncome: number;
  totalExpense: number;
  totalSavings: number;
  balance: number;
}

export const DEFAULT_EXPENSE_CATEGORIES = [
  'Food & Dining',
  'Rent & Housing',
  'Transportation',
  'Utilities',
  'Entertainment',
  'Healthcare',
  'Shopping',
  'Education',
  'Travel',
  'Insurance',
  'Subscriptions',
  'Personal Care',
  'Gifts & Donations',
  'Taxes',
  'Debt Payments',
  'Others'
];

export const DEFAULT_INCOME_CATEGORIES = [
  'Salary',
  'Freelance',
  'Investments',
  'Dividends',
  'Royalties',
  'Grants',
  'Rental Income',
  'Refunds',
  'Gifts',
  'Other Income',
  'Savings Withdrawal'
];

export const DEFAULT_SAVINGS_CATEGORIES = [
  'Goal Saving',
  'Emergency Fund',
  'Bank Deposit',
  'Fixed Deposit',
  'DPS',
  'Investments',
  'Gold',
  'Stocks',
  'Cash Savings',
  'Crypto',
  'Retirement'
];

// Bangla Translations for Default Categories
export const CATEGORY_TRANSLATIONS_BN: Record<string, string> = {
  // Expenses
  'Food & Dining': 'খাবার ও রেস্তোরা',
  'Rent & Housing': 'বাড়ি ভাড়া ও আবাসন',
  'Transportation': 'পরিবহন',
  'Utilities': 'বিল ও ইউটিলিটি',
  'Entertainment': 'বিনোদন',
  'Healthcare': 'চিকিৎসা',
  'Shopping': 'কেনাকাটা',
  'Education': 'শিক্ষা',
  'Travel': 'ভ্রমণ',
  'Insurance': 'বীমা',
  'Subscriptions': 'সাবস্ক্রিপশন',
  'Personal Care': 'ব্যক্তিগত যত্ন',
  'Gifts & Donations': 'উপহার ও দান',
  'Taxes': 'ট্যাক্স',
  'Debt Payments': 'ঋণ পরিশোধ',
  'Others': 'অন্যান্য',

  // Income
  'Salary': 'বেতন',
  'Freelance': 'ফ্রিল্যান্সিং',
  'Investments': 'বিনিয়োগ',
  'Dividends': 'লভ্যাংশ',
  'Royalties': 'রয়্যালটি',
  'Grants': 'অনুদান',
  'Rental Income': 'ভাড়া আয়',
  'Refunds': 'রিফান্ড',
  'Gifts': 'উপহার',
  'Other Income': 'অন্যান্য আয়',
  'Savings Withdrawal': 'সঞ্চয় থেকে উত্তোলন',

  // Savings
  'Emergency Fund': 'জরুরী তহবিল',
  'Bank Deposit': 'ব্যাংক জমা',
  'DPS': 'ডিপিএস',
  'Gold': 'স্বর্ণ',
  'Stocks': 'শেয়ার বাজার',
  'Cash Savings': 'নগদ জমা',
  'Crypto': 'ক্রিপ্টো',
  'Retirement': 'অবসরকালীন',
  'Goal Saving': 'লক্ষ্য সঞ্চয়',
  'Fixed Deposit': 'ফিক্সড ডিপোজিট'
};

export const getLocalizedCategory = (category: string, language: Language): string => {
  if (language === 'bn') {
    return CATEGORY_TRANSLATIONS_BN[category] || category;
  }
  return category;
};

export const CURRENCIES = [
  { code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka' },
  { code: 'USD', symbol: '$', name: 'US Dollar' },
  { code: 'EUR', symbol: '€', name: 'Euro' },
  { code: 'GBP', symbol: '£', name: 'British Pound' },
  { code: 'INR', symbol: '₹', name: 'Indian Rupee' },
  { code: 'JPY', symbol: '¥', name: 'Japanese Yen' },
  { code: 'CAD', symbol: 'C$', name: 'Canadian Dollar' },
  { code: 'AUD', symbol: 'A$', name: 'Australian Dollar' }
];

export const EXCHANGE_RATES: Record<string, number> = {
  USD: 1,
  BDT: 122.50,
  EUR: 0.96,
  GBP: 0.81,
  INR: 86.85,
  JPY: 154.50,
  CAD: 1.44,
  AUD: 1.60
};

export const convertAmount = (amount: number, fromCurrency: string, toCurrency: string): number => {
  const fromRate = EXCHANGE_RATES[fromCurrency] || 1;
  const toRate = EXCHANGE_RATES[toCurrency] || 1;
  return (amount / fromRate) * toRate;
};

export type Language = 'en' | 'bn' | 'hi' | 'fr' | 'es' | 'de' | 'ja';

const EN_TRANSLATIONS = {
    dashboard: {
      balance: 'Current Balance',
      income: 'Total Income',
      expense: 'Total Expense',
      savings: 'Total Savings',
    },
    form: {
      title: 'Add Transaction',
      editTitle: 'Edit Transaction',
      income: 'Income',
      expense: 'Expense',
      savings: 'Savings',
      amount: 'Amount',
      category: 'Category',
      date: 'Date',
      note: 'Note (Optional)',
      addBtn: 'Add Transaction',
      updateBtn: 'Update Transaction',
      cancelBtn: 'Cancel',
      placeholderAmount: '0.00',
      placeholderNote: 'e.g., Grocery shopping',
      alertAmount: 'Please enter a valid positive amount.',
      alertCategory: 'Please select a category.',
      deductFromBalance: 'Deduct from Balance?',
      deductDesc: 'Money will be subtracted from your current balance.',
      noDeductDesc: 'Just adds to savings category. Balance remains unchanged.',
    },
    list: {
      title: 'Recent History',
      emptyTitle: 'No transactions yet',
      emptyDesc: 'Add your first income, expense or savings to start tracking.',
      deleteTitle: 'Delete Transaction',
      deleteConfirm: 'Are you sure you want to delete this transaction?',
      confirm: 'Confirm',
      cancel: 'Cancel'
    },
    chart: {
      title: 'Spending by Category',
      empty: 'Add expenses to see the spending breakdown.',
      tooltipAmount: 'Amount'
    },
    goals: {
      title: 'Funds & Savings',
      empty: 'No savings goals yet.',
      saved: 'Saved',
      target: 'Target',
      completed: 'Completed!',
      addMoney: 'Deposit',
      create: 'Add New Fund',
      edit: 'Edit Fund',
      update: 'Update',
      name: 'Fund Name',
      placeholderName: 'e.g. New Laptop or FD',
      deleteConfirm: 'Are you sure you want to delete this fund?',
      depositTitle: 'Deposit to Fund',
      depositBtn: 'Deposit',
      withdrawBtn: 'Withdraw',
      withdrawTitle: 'Withdraw from Fund',
      isFixedDeposit: 'Mark as Fixed Deposit (FD)',
      fdDesc: 'Money will be locked. Confirmation required to break.',
      breakFdTitle: 'Break Fixed Deposit?',
      breakFdConfirm: 'Are you sure you want to break this Fixed Deposit early?',
      confirmWithdraw: 'Withdraw funds to main balance?',
      fixedDeposit: 'Fixed Deposit',
      category: 'Savings Category'
    },
    funds: {
      title: 'Funds & Savings',
      emptyGoals: 'No funds goals yet.',
      saved: 'Saved',
      target: 'Target',
      addMoney: 'Add Money',
      addGoal: 'Add Goal',
      editGoal: 'Edit Goal',
      create: 'Create',
      update: 'Update',
      goalName: 'Goal Name',
      deposit: 'Deposit',
      deleteGoalConfirm: 'Are you sure you want to delete this goal?'
    },
    ai: {
      title: 'AI Financial Insights',
      desc: 'Ask questions or get tips based on your spending habits using Gemini AI.',
      btn: 'Generate Tip',
      askBtn: 'Ask AI',
      placeholder: 'Ask a question (e.g. How to save more?)',
      analyzing: 'Thinking...',
      error: 'Could not retrieve insight at this moment.',
      apiError: 'I\'m having trouble analyzing your data right now. Please try again later.',
      missingKey: 'API Key is missing.'
    },
    settings: {
      title: 'Settings',
      generalTab: 'General',
      categoriesTab: 'Categories',
      appearance: 'Appearance',
      darkMode: 'Dark Mode',
      sound: 'Sound Effects',
      language: 'Language',
      currency: 'Currency',
      selectCurrency: 'Select Currency',
      incomeTab: 'Income',
      expenseTab: 'Expense',
      savingsTab: 'Savings',
      placeholder: 'New category name...',
      add: 'Add',
      close: 'Close',
      exists: 'Category already exists.',
      deleteTitle: 'Delete Category',
      deleteConfirm: 'Are you sure you want to remove this category?',
      dataManagement: 'Data Management',
      backupTitle: 'Backup & Restore',
      backupDesc: 'Save your data or transfer to another device.',
      backupEmail: 'Backup via Email',
      restoreData: 'Restore Data',
      clearData: 'Reset Transactions',
      clearDataDesc: 'Delete all transactions for this profile but keep settings.',
      confirmClearTitle: 'Reset Transactions?',
      confirmClearDesc: 'This will delete all income and expense entries for the current profile. Categories and settings will be saved.',
      confirmRestoreTitle: 'Restore Data?',
      confirmRestoreDesc: 'This will replace your current data with the backup file. Are you sure?',
      successRestore: 'Data restored successfully!',
      errorRestore: 'Invalid backup file.',
      shareExport: 'Share & Export',
      openShare: 'Open Share Options',
      logout: 'Logout',
      logoutConfirm: 'Are you sure you want to logout?'
    },
    profile: {
      title: 'Profile Manager',
      create: 'Create Profile',
      switch: 'Switch',
      edit: 'Edit',
      update: 'Update',
      delete: 'Delete',
      namePlaceholder: 'Profile Name (e.g. Travel)',
      deleteTitle: 'Delete Profile',
      confirmDelete: 'Are you sure? All data for this profile will be lost.',
      active: 'Active',
      cantDeleteLast: 'Cannot delete the only profile.'
    },
    share: {
      title: 'Share & Export',
      desc: 'Export your financial data or share a summary.',
      exportCsv: 'Export CSV',
      copySummary: 'Copy Summary',
      csvDesc: 'Download all transactions as a spreadsheet.',
      summaryDesc: 'Copy a text report to clipboard.',
      copied: 'Copied!',
      totalBalance: 'Total Balance',
      netIncome: 'Net Income',
      netExpense: 'Net Expense',
      totalSavings: 'Total Savings',
      exportPdf: 'Export PDF',
      pdfDesc: 'Download a detailed PDF report.',
      sharePdf: 'Share PDF File',
      sharePdfDesc: 'Send PDF via Gmail, WhatsApp, etc.',
      shareWhatsapp: 'Share on WhatsApp',
      shareWhatsappDesc: 'Send summary text via WhatsApp.',
      shareMail: 'Send Email',
      shareMailDesc: 'Send summary text via Email.'
    },
    calculator: {
      title: 'Calculator',
      copy: 'Copy',
      copied: 'Copied!',
      clear: 'AC',
      error: 'Error'
    },
    common: {
      soundOn: 'Sound On',
      soundOff: 'Sound Off',
      on: 'On',
      off: 'Off',
      confirm: 'Confirm',
      cancel: 'Cancel',
      note: 'Note'
    }
};

const BN_TRANSLATIONS = {
    dashboard: {
      balance: 'বর্তমান ব্যালেন্স',
      income: 'মোট আয়',
      expense: 'মোট ব্যয়',
      savings: 'মোট সঞ্চয়',
    },
    form: {
      title: 'লেনদেন যোগ করুন',
      editTitle: 'লেনদেন আপডেট করুন',
      income: 'আয়',
      expense: 'ব্যয়',
      savings: 'সঞ্চয়',
      amount: 'পরিমাণ',
      category: 'বিভাগ',
      date: 'তারিখ',
      note: 'নোট (ঐচ্ছিক)',
      addBtn: 'লেনদেন যোগ করুন',
      updateBtn: 'আপডেট করুন',
      cancelBtn: 'বাতিল',
      placeholderAmount: '০.০০',
      placeholderNote: 'যেমন: বাজার খরচ',
      alertAmount: 'অনুগ্রহ করে সঠিক পরিমাণ লিখুন।',
      alertCategory: 'অনুগ্রহ করে একটি বিভাগ নির্বাচন করুন।',
      deductFromBalance: 'ব্যালেন্স থেকে কাটবে?',
      deductDesc: 'টাকা বর্তমান ব্যালেন্স থেকে কমে যাবে।',
      noDeductDesc: 'শুধুমাত্র সঞ্চয় ক্যাটাগরিতে যোগ হবে। ব্যালেন্স কমবে না।',
    },
    list: {
      title: 'সাম্প্রতিক ইতিহাস',
      emptyTitle: 'কোনো লেনদেন নেই',
      emptyDesc: 'ট্র্যাকিং শুরু করতে আপনার প্রথম আয়, ব্যয় বা সঞ্চয় যোগ করুন।',
      deleteTitle: 'লেনদেন মুছুন',
      deleteConfirm: 'আপনি কি নিশ্চিত যে আপনি এই লেনদেনটি মুছে ফেলতে চান?',
      confirm: 'নিশ্চিত করুন',
      cancel: 'বাতিল'
    },
    chart: {
      title: 'বিভাগ অনুযায়ী খরচ',
      empty: 'খরচের বিবরণ দেখতে ব্যয় যোগ করুন।',
      tooltipAmount: 'পরিমাণ'
    },
    goals: {
      title: 'তহবিল ও সঞ্চয়',
      empty: 'কোনো সঞ্চয় তহবিল নেই।',
      saved: 'জমা',
      target: 'লক্ষ্য',
      completed: 'সম্পন্ন!',
      addMoney: 'জমা করুন',
      create: 'নতুন তহবিল যোগ করুন',
      edit: 'তহবিল আপডেট',
      update: 'আপডেট',
      name: 'তহবিলের নাম',
      placeholderName: 'যেমন: নতুন ল্যাপটপ বা এফডি',
      deleteConfirm: 'আপনি কি নিশ্চিত যে আপনি এই তহবিলটি মুছে ফেলতে চান?',
      depositTitle: 'তহবিলে জমা দিন',
      depositBtn: 'জমা দিন',
      withdrawBtn: 'উত্তোলন করুন',
      withdrawTitle: 'তহবিল থেকে উত্তোলন',
      isFixedDeposit: 'ফিক্সড ডিপোজিট (FD) হিসেবে মার্ক করুন',
      fdDesc: 'টাকা লক থাকবে। ভাঙার জন্য নিশ্চিতকরণের প্রয়োজন হবে।',
      breakFdTitle: 'ফিক্সড ডিপোজিট ভাঙবেন?',
      breakFdConfirm: 'আপনি কি নিশ্চিত যে আপনি মেয়াদের আগেই এই ফিক্সড ডিপোজিট ভাঙতে চান?',
      confirmWithdraw: 'টাকা বর্তমান ব্যালেন্সে ফেরত আসবে?',
      fixedDeposit: 'ফিক্সড ডিপোজিট',
      category: 'সঞ্চয় বিভাগ'
    },
    funds: {
      title: 'তহবিল ও সঞ্চয়',
      emptyGoals: 'কোনো তহবিল নেই।',
      saved: 'জমা',
      target: 'লক্ষ্য',
      addMoney: 'টাকা যোগ',
      addGoal: 'তহবিল যোগ',
      editGoal: 'তহবিল আপডেট',
      create: 'তৈরি',
      update: 'আপডেট',
      goalName: 'তহবিলের নাম',
      deposit: 'জমা',
      deleteGoalConfirm: 'আপনি কি নিশ্চিত যে আপনি এই তহবিলটি মুছে ফেলতে চান?'
    },
    ai: {
      title: 'এআই আর্থিক পরামর্শ',
      desc: 'জেমিনি এআই ব্যবহার করে আপনার প্রশ্ন জিজ্ঞাসা করুন বা টিপস পান।',
      btn: 'পরামর্শ তৈরি করুন',
      askBtn: 'জিজ্ঞাসা করুন',
      placeholder: 'প্রশ্ন করুন (যেমন: আমি কীভাবে আরও সঞ্চয় করতে পারি?)',
      analyzing: 'ভাবছি...',
      error: 'এই মুহূর্তে পরামর্শ পাওয়া যাচ্ছে না।',
      apiError: 'আপনার তথ্য বিশ্লেষণ করতে সমস্যা হচ্ছে। অনুগ্রহ করে পরে আবার চেষ্টা করুন।',
      missingKey: 'এপিআই কি (API Key) পাওয়া যায়নি।'
    },
    settings: {
      title: 'সেটিংস',
      generalTab: 'সাধারণ',
      categoriesTab: 'বিভাগ',
      appearance: 'চেহারা',
      darkMode: 'ডার্ক মোড',
      sound: 'সাউন্ড ইফেক্ট',
      language: 'ভাষা',
      currency: 'মুদ্রা',
      selectCurrency: 'মুদ্রা নির্বাচন করুন',
      incomeTab: 'আয়',
      expenseTab: 'ব্যয়',
      savingsTab: 'সঞ্চয়',
      placeholder: 'নতুন বিভাগের নাম...',
      add: 'যোগ করুন',
      close: 'বন্ধ করুন',
      exists: 'এই বিভাগটি ইতিমধ্যে বিদ্যমান।',
      deleteTitle: 'বিভাগ মুছুন',
      deleteConfirm: 'আপনি কি নিশ্চিত যে আপনি এই বিভাগটি মুছে ফেলতে চান?',
      dataManagement: 'ডেটা ম্যানেজমেন্ট',
      backupTitle: 'ব্যাকআপ এবং রিস্টোর',
      backupDesc: 'আপনার তথ্য সংরক্ষণ করুন বা অন্য ডিভাইসে স্থানান্তর করুন।',
      backupEmail: 'ব্যাকআপ (ইমেইল)',
      restoreData: 'ডেটা রিস্টোর করুন',
      clearData: 'লেনদেন রিসেট করুন',
      clearDataDesc: 'এই প্রোফাইলের সব লেনদেন মুছে ফেলুন, কিন্তু সেটিংস ঠিক থাকবে।',
      confirmClearTitle: 'লেনদেন রিসেট করবেন?',
      confirmClearDesc: 'এটি বর্তমান প্রোফাইলের সমস্ত লেনদেন মুছে ফেলবে। বিভাগ এবং সেটিংস সংরক্ষিত থাকবে।',
      confirmRestoreTitle: 'ডেটা রিস্টোর করবেন?',
      confirmRestoreDesc: 'এটি আপনার বর্তমান ডেটা ব্যাকআপ ফাইলের সাথে প্রতিস্থাপন করবে। আপনি কি নিশ্চিত?',
      successRestore: 'ডেটা সফলভাবে রিস্টোর করা হয়েছে!',
      errorRestore: 'অকার্যকর ব্যাকআপ ফাইল।',
      shareExport: 'শেয়ার এবং এক্সপোর্ট',
      openShare: 'শেয়ার অপশন খুলুন',
      logout: 'লগআউট',
      logoutConfirm: 'আপনি কি নিশ্চিত যে আপনি লগআউট করতে চান?'
    },
    profile: {
      title: 'প্রোফাইল ম্যানেজার',
      create: 'প্রোফাইল তৈরি করুন',
      switch: 'পরিবর্তন',
      edit: 'এডিট',
      update: 'আপডেট',
      delete: 'মুছুন',
      namePlaceholder: 'প্রোফাইলের নাম (যেমন: ভ্রমণ)',
      deleteTitle: 'প্রোফাইল মুছুন',
      confirmDelete: 'আপনি কি নিশ্চিত? এই প্রোফাইলের সব তথ্য মুছে যাবে।',
      active: 'সক্রিয়',
      cantDeleteLast: 'একমাত্র প্রোফাইলটি মুছে ফেলা যাবে না।'
    },
    share: {
      title: 'শেয়ার এবং এক্সপোর্ট',
      desc: 'আপনার তথ্য এক্সপোর্ট করুন বা শেয়ার করুন।',
      exportCsv: 'CSV এক্সপোর্ট',
      copySummary: 'সারাংশ কপি করুন',
      csvDesc: 'স্প্রেডশিট হিসেবে সব লেনদেন ডাউনলোড করুন।',
      summaryDesc: 'ক্লিপবোর্ডে রিপোর্ট কপি করুন।',
      copied: 'কপি করা হয়েছে!',
      totalBalance: 'মোট ব্যালেন্স',
      netIncome: 'নীট আয়',
      netExpense: 'নীট ব্যয়',
      totalSavings: 'মোট সঞ্চয়',
      exportPdf: 'পিডিএফ (PDF) এক্সপোর্ট',
      pdfDesc: 'বিস্তারিত পিডিএফ রিপোর্ট ডাউনলোড করুন।',
      sharePdf: 'পিডিএফ শেয়ার করুন',
      sharePdfDesc: 'জিমেইল, হোয়াটসঅ্যাপ বা মেসেঞ্জারে পাঠান।',
      shareWhatsapp: 'হোয়াটসঅ্যাপ',
      shareWhatsappDesc: 'হোয়াটসঅ্যাপে সারাংশ পাঠান।',
      shareMail: 'ইমেইল',
      shareMailDesc: 'ইমেইলে সারাংশ পাঠান।'
    },
    calculator: {
      title: 'ক্যালকুলেটর',
      copy: 'কপি করুন',
      copied: 'কপি হয়েছে!',
      clear: 'AC',
      error: 'ত্রুটি'
    },
    common: {
      soundOn: 'সাউন্ড চালু',
      soundOff: 'সাউন্ড বন্ধ',
      on: 'চালু',
      off: 'বন্ধ',
      confirm: 'নিশ্চিত করুন',
      cancel: 'বাতিল',
      note: 'নোট'
    }
};

const DE_TRANSLATIONS = {
    dashboard: {
      balance: 'Aktueller Stand',
      income: 'Einkommen',
      expense: 'Ausgaben',
      savings: 'Ersparnisse',
    },
    form: {
      title: 'Transaktion hinzufügen',
      editTitle: 'Transaktion bearbeiten',
      income: 'Einkommen',
      expense: 'Ausgabe',
      savings: 'Sparen',
      amount: 'Betrag',
      category: 'Kategorie',
      date: 'Datum',
      note: 'Notiz (Optional)',
      addBtn: 'Hinzufügen',
      updateBtn: 'Aktualisieren',
      cancelBtn: 'Abbrechen',
      placeholderAmount: '0.00',
      placeholderNote: 'z.B. Lebensmittel',
      alertAmount: 'Bitte geben Sie einen gültigen Betrag ein.',
      alertCategory: 'Bitte wählen Sie eine Kategorie.',
      deductFromBalance: 'Vom Guthaben abziehen?',
      deductDesc: 'Geld wird vom aktuellen Saldo abgezogen.',
      noDeductDesc: 'Fügt nur zur Sparkategorie hinzu. Saldo bleibt gleich.',
    },
    list: {
      title: 'Verlauf',
      emptyTitle: 'Keine Transaktionen',
      emptyDesc: 'Fügen Sie Einnahmen oder Ausgaben hinzu.',
      deleteTitle: 'Löschen',
      deleteConfirm: 'Möchten Sie diese Transaktion wirklich löschen?',
      confirm: 'Bestätigen',
      cancel: 'Abbrechen'
    },
    chart: {
      title: 'Ausgaben nach Kategorie',
      empty: 'Fügen Sie Ausgaben hinzu, um Details zu sehen.',
      tooltipAmount: 'Betrag'
    },
    goals: {
      title: 'Fonds & Ersparnisse',
      empty: 'Noch keine Sparziele.',
      saved: 'Gespart',
      target: 'Ziel',
      completed: 'Erledigt!',
      addMoney: 'Einzahlen',
      create: 'Neuer Fonds',
      edit: 'Bearbeiten',
      update: 'Aktualisieren',
      name: 'Fondsname',
      placeholderName: 'z.B. Neuer Laptop',
      deleteConfirm: 'Diesen Fonds wirklich löschen?',
      depositTitle: 'Einzahlen',
      depositBtn: 'Einzahlen',
      withdrawBtn: 'Abheben',
      withdrawTitle: 'Vom Fonds abheben',
      isFixedDeposit: 'Als Festgeld (FD) markieren',
      fdDesc: 'Geld wird gesperrt. Bestätigung zum Auflösen erforderlich.',
      breakFdTitle: 'Festgeld auflösen?',
      breakFdConfirm: 'Möchten Sie dieses Festgeld wirklich vorzeitig auflösen?',
      confirmWithdraw: 'Geld auf das Hauptkonto zurückbuchen?',
      fixedDeposit: 'Festgeld',
      category: 'Sparkategorie'
    },
    funds: {
      title: 'Fonds & Ersparnisse',
      emptyGoals: 'Keine Fondsziele.',
      saved: 'Gespart',
      target: 'Ziel',
      addMoney: 'Geld hinzufügen',
      addGoal: 'Ziel hinzufügen',
      editGoal: 'Ziel bearbeiten',
      create: 'Erstellen',
      update: 'Aktualisieren',
      goalName: 'Zielname',
      deposit: 'Einzahlung',
      deleteGoalConfirm: 'Ziel wirklich löschen?'
    },
    ai: {
      title: 'KI Finanz-Einblicke',
      desc: 'Fragen Sie Gemini AI nach Tipps zu Ihren Ausgaben.',
      btn: 'Tipp generieren',
      askBtn: 'KI fragen',
      placeholder: 'Stellen Sie eine Frage (z.B. Wie spare ich mehr?)',
      analyzing: 'Nachdenken...',
      error: 'Konnte keinen Einblick erhalten.',
      apiError: 'Problem bei der Datenanalyse. Bitte später versuchen.',
      missingKey: 'API-Schlüssel fehlt.'
    },
    settings: {
      title: 'Einstellungen',
      generalTab: 'Allgemein',
      categoriesTab: 'Kategorien',
      appearance: 'Erscheinungsbild',
      darkMode: 'Dunkelmodus',
      sound: 'Soundeffekte',
      language: 'Sprache',
      currency: 'Währung',
      selectCurrency: 'Währung wählen',
      incomeTab: 'Einkommen',
      expenseTab: 'Ausgabe',
      savingsTab: 'Sparen',
      placeholder: 'Neue Kategorie...',
      add: 'Hinzufügen',
      close: 'Schließen',
      exists: 'Kategorie existiert bereits.',
      deleteTitle: 'Kategorie löschen',
      deleteConfirm: 'Diese Kategorie entfernen?',
      dataManagement: 'Datenverwaltung',
      backupTitle: 'Sichern & Wiederherstellen',
      backupDesc: 'Daten speichern oder übertragen.',
      backupEmail: 'Backup per E-Mail',
      restoreData: 'Daten wiederherstellen',
      clearData: 'Zurücksetzen',
      clearDataDesc: 'Alle Transaktionen löschen.',
      confirmClearTitle: 'Zurücksetzen?',
      confirmClearDesc: 'Dies löscht alle Einträge. Einstellungen bleiben erhalten.',
      confirmRestoreTitle: 'Wiederherstellen?',
      confirmRestoreDesc: 'Dies ersetzt aktuelle Daten durch das Backup.',
      successRestore: 'Daten wiederhergestellt!',
      errorRestore: 'Ungültige Datei.',
      shareExport: 'Teilen & Export',
      openShare: 'Teilen-Optionen',
      logout: 'Abmelden',
      logoutConfirm: 'Möchten Sie sich wirklich abmelden?'
    },
    profile: {
      title: 'Profilmanager',
      create: 'Profil erstellen',
      switch: 'Wechseln',
      edit: 'Bearbeiten',
      update: 'Aktualisieren',
      delete: 'Löschen',
      namePlaceholder: 'Profilname',
      deleteTitle: 'Profil löschen',
      confirmDelete: 'Sicher? Alle Daten gehen verloren.',
      active: 'Aktiv',
      cantDeleteLast: 'Kann das letzte Profil nicht löschen.'
    },
    share: {
      title: 'Teilen & Export',
      desc: 'Exportieren oder teilen Sie Ihre Daten.',
      exportCsv: 'CSV Export',
      copySummary: 'Zusammenfassung kopieren',
      csvDesc: 'Als Tabelle herunterladen.',
      summaryDesc: 'Bericht in die Zwischenablage kopieren.',
      copied: 'Kopiert!',
      totalBalance: 'Gesamtsaldo',
      netIncome: 'Nettoeinkommen',
      netExpense: 'Nettoausgaben',
      totalSavings: 'Gesamtersparnisse',
      exportPdf: 'PDF Export',
      pdfDesc: 'Detaillierten PDF-Bericht laden.',
      sharePdf: 'PDF teilen',
      sharePdfDesc: 'Per E-Mail oder WhatsApp senden.',
      shareWhatsapp: 'WhatsApp',
      shareWhatsappDesc: 'Zusammenfassung per WhatsApp.',
      shareMail: 'E-Mail',
      shareMailDesc: 'Zusammenfassung per E-Mail.'
    },
    calculator: {
      title: 'Taschenrechner',
      copy: 'Kopieren',
      copied: 'Kopiert!',
      clear: 'AC',
      error: 'Fehler'
    },
    common: {
      soundOn: 'Ton an',
      soundOff: 'Ton aus',
      on: 'An',
      off: 'Aus',
      confirm: 'Bestätigen',
      cancel: 'Abbrechen',
      note: 'Notiz'
    }
};

const ES_TRANSLATIONS = {
    dashboard: {
      balance: 'Saldo Actual',
      income: 'Ingresos Totales',
      expense: 'Gastos Totales',
      savings: 'Ahorro Total',
    },
    form: {
      title: 'Añadir Transacción',
      editTitle: 'Editar Transacción',
      income: 'Ingreso',
      expense: 'Gasto',
      savings: 'Ahorro',
      amount: 'Cantidad',
      category: 'Categoría',
      date: 'Fecha',
      note: 'Nota (Opcional)',
      addBtn: 'Añadir',
      updateBtn: 'Actualizar',
      cancelBtn: 'Cancelar',
      placeholderAmount: '0.00',
      placeholderNote: 'ej. Compras',
      alertAmount: 'Por favor ingrese una cantidad válida.',
      alertCategory: 'Seleccione una categoría.',
      deductFromBalance: '¿Deducir del saldo?',
      deductDesc: 'El dinero se restará del saldo actual.',
      noDeductDesc: 'Solo añade a ahorros. El saldo no cambia.',
    },
    list: {
      title: 'Historial',
      emptyTitle: 'Sin transacciones',
      emptyDesc: 'Añade tus primeros ingresos o gastos.',
      deleteTitle: 'Eliminar',
      deleteConfirm: '¿Seguro que quieres eliminar esto?',
      confirm: 'Confirmar',
      cancel: 'Cancelar'
    },
    chart: {
      title: 'Gastos por Categoría',
      empty: 'Añade gastos para ver el gráfico.',
      tooltipAmount: 'Cantidad'
    },
    goals: {
      title: 'Fondos y Ahorros',
      empty: 'Sin metas de ahorro.',
      saved: 'Ahorrado',
      target: 'Meta',
      completed: '¡Completado!',
      addMoney: 'Depositar',
      create: 'Nuevo Fondo',
      edit: 'Editar',
      update: 'Actualizar',
      name: 'Nombre del Fondo',
      placeholderName: 'ej. Nuevo Laptop',
      deleteConfirm: '¿Eliminar este fondo?',
      depositTitle: 'Depositar',
      depositBtn: 'Depositar',
      withdrawBtn: 'Retirar',
      withdrawTitle: 'Retirar del Fondo',
      isFixedDeposit: 'Marcar como Depósito Fijo (FD)',
      fdDesc: 'Dinero bloqueado. Requiere confirmación para romper.',
      breakFdTitle: '¿Romper Depósito Fijo?',
      breakFdConfirm: '¿Seguro que quieres romper este depósito antes de tiempo?',
      confirmWithdraw: '¿Retirar fondos al saldo principal?',
      fixedDeposit: 'Depósito Fijo',
      category: 'Categoría de Ahorro'
    },
    funds: {
      title: 'Fondos',
      emptyGoals: 'Sin fondos.',
      saved: 'Ahorrado',
      target: 'Meta',
      addMoney: 'Añadir Dinero',
      addGoal: 'Añadir Meta',
      editGoal: 'Editar Meta',
      create: 'Crear',
      update: 'Actualizar',
      goalName: 'Nombre',
      deposit: 'Depósito',
      deleteGoalConfirm: '¿Eliminar meta?'
    },
    ai: {
      title: 'Consejos Financieros IA',
      desc: 'Pregunta a Gemini AI sobre tus gastos.',
      btn: 'Generar Consejo',
      askBtn: 'Preguntar IA',
      placeholder: 'Haz una pregunta (ej. ¿Cómo ahorrar más?)',
      analyzing: 'Pensando...',
      error: 'No se pudo obtener consejo.',
      apiError: 'Error al analizar datos. Intenta más tarde.',
      missingKey: 'Falta la clave API.'
    },
    settings: {
      title: 'Ajustes',
      generalTab: 'General',
      categoriesTab: 'Categorías',
      appearance: 'Apariencia',
      darkMode: 'Modo Oscuro',
      sound: 'Sonidos',
      language: 'Idioma',
      currency: 'Moneda',
      selectCurrency: 'Seleccionar Moneda',
      incomeTab: 'Ingreso',
      expenseTab: 'Gasto',
      savingsTab: 'Ahorro',
      placeholder: 'Nueva categoría...',
      add: 'Añadir',
      close: 'Cerrar',
      exists: 'La categoría ya existe.',
      deleteTitle: 'Eliminar Categoría',
      deleteConfirm: '¿Eliminar esta categoría?',
      dataManagement: 'Gestión de Datos',
      backupTitle: 'Copia de Seguridad',
      backupDesc: 'Guardar o transferir datos.',
      backupEmail: 'Respaldo por Email',
      restoreData: 'Restaurar Datos',
      clearData: 'Reiniciar',
      clearDataDesc: 'Borrar todas las transacciones.',
      confirmClearTitle: '¿Reiniciar?',
      confirmClearDesc: 'Esto borrará todas las entradas. Los ajustes se guardan.',
      confirmRestoreTitle: '¿Restaurar?',
      confirmRestoreDesc: 'Esto reemplazará los datos actuales.',
      successRestore: '¡Datos restaurados!',
      errorRestore: 'Archivo inválido.',
      shareExport: 'Compartir y Exportar',
      openShare: 'Opciones de Compartir',
      logout: 'Cerrar Sesión',
      logoutConfirm: '¿Seguro que quieres salir?'
    },
    profile: {
      title: 'Gestor de Perfiles',
      create: 'Crear Perfil',
      switch: 'Cambiar',
      edit: 'Editar',
      update: 'Actualizar',
      delete: 'Eliminar',
      namePlaceholder: 'Nombre del Perfil',
      deleteTitle: 'Eliminar Perfil',
      confirmDelete: '¿Seguro? Se perderán los datos.',
      active: 'Activo',
      cantDeleteLast: 'No se puede eliminar el último perfil.'
    },
    share: {
      title: 'Compartir',
      desc: 'Exporta o comparte tus datos.',
      exportCsv: 'Exportar CSV',
      copySummary: 'Copiar Resumen',
      csvDesc: 'Descargar como hoja de cálculo.',
      summaryDesc: 'Copiar reporte al portapapeles.',
      copied: '¡Copiado!',
      totalBalance: 'Saldo Total',
      netIncome: 'Ingreso Neto',
      netExpense: 'Gasto Neto',
      totalSavings: 'Ahorro Total',
      exportPdf: 'Exportar PDF',
      pdfDesc: 'Descargar reporte detallado.',
      sharePdf: 'Compartir PDF',
      sharePdfDesc: 'Enviar por Email o WhatsApp.',
      shareWhatsapp: 'WhatsApp',
      shareWhatsappDesc: 'Enviar resumen por WhatsApp.',
      shareMail: 'Email',
      shareMailDesc: 'Enviar resumen por Email.'
    },
    calculator: {
      title: 'Calculadora',
      copy: 'Copiar',
      copied: '¡Copiado!',
      clear: 'AC',
      error: 'Error'
    },
    common: {
      soundOn: 'Sonido On',
      soundOff: 'Sonido Off',
      on: 'On',
      off: 'Off',
      confirm: 'Confirmar',
      cancel: 'Cancelar',
      note: 'Nota'
    }
};

const FR_TRANSLATIONS = {
    dashboard: {
      balance: 'Solde Actuel',
      income: 'Revenus Totaux',
      expense: 'Dépenses Totales',
      savings: 'Épargne Totale',
    },
    form: {
      title: 'Ajouter Transaction',
      editTitle: 'Modifier Transaction',
      income: 'Revenu',
      expense: 'Dépense',
      savings: 'Épargne',
      amount: 'Montant',
      category: 'Catégorie',
      date: 'Date',
      note: 'Note (Optionnel)',
      addBtn: 'Ajouter',
      updateBtn: 'Mettre à jour',
      cancelBtn: 'Annuler',
      placeholderAmount: '0.00',
      placeholderNote: 'ex. Courses',
      alertAmount: 'Veuillez entrer un montant valide.',
      alertCategory: 'Veuillez sélectionner une catégorie.',
      deductFromBalance: 'Déduire du solde?',
      deductDesc: 'L\'argent sera soustrait du solde actuel.',
      noDeductDesc: 'Ajoute seulement à l\'épargne. Le solde reste inchangé.',
    },
    list: {
      title: 'Historique',
      emptyTitle: 'Aucune transaction',
      emptyDesc: 'Ajoutez vos premiers revenus ou dépenses.',
      deleteTitle: 'Supprimer',
      deleteConfirm: 'Voulez-vous vraiment supprimer ceci?',
      confirm: 'Confirmer',
      cancel: 'Annuler'
    },
    chart: {
      title: 'Dépenses par Catégorie',
      empty: 'Ajoutez des dépenses pour voir le graphique.',
      tooltipAmount: 'Montant'
    },
    goals: {
      title: 'Fonds et Épargne',
      empty: 'Pas d\'objectifs d\'épargne.',
      saved: 'Épargné',
      target: 'Objectif',
      completed: 'Terminé!',
      addMoney: 'Déposer',
      create: 'Nouveau Fonds',
      edit: 'Modifier',
      update: 'Mettre à jour',
      name: 'Nom du Fonds',
      placeholderName: 'ex. Nouvel Ordi',
      deleteConfirm: 'Supprimer ce fonds?',
      depositTitle: 'Déposer',
      depositBtn: 'Déposer',
      withdrawBtn: 'Retirer',
      withdrawTitle: 'Retirer du Fonds',
      isFixedDeposit: 'Marquer comme Dépôt Fixe (FD)',
      fdDesc: 'Argent bloqué. Confirmation requise pour casser.',
      breakFdTitle: 'Casser le Dépôt Fixe?',
      breakFdConfirm: 'Voulez-vous vraiment casser ce dépôt avant terme?',
      confirmWithdraw: 'Retirer les fonds vers le solde principal?',
      fixedDeposit: 'Dépôt Fixe',
      category: 'Catégorie d\'Épargne'
    },
    funds: {
      title: 'Fonds',
      emptyGoals: 'Aucun fonds.',
      saved: 'Épargné',
      target: 'Objectif',
      addMoney: 'Ajouter',
      addGoal: 'Ajouter Objectif',
      editGoal: 'Modifier',
      create: 'Créer',
      update: 'Mettre à jour',
      goalName: 'Nom',
      deposit: 'Dépôt',
      deleteGoalConfirm: 'Supprimer l\'objectif?'
    },
    ai: {
      title: 'Conseils Financiers IA',
      desc: 'Demandez à Gemini AI des conseils sur vos dépenses.',
      btn: 'Générer Conseil',
      askBtn: 'Demander IA',
      placeholder: 'Posez une question (ex. Comment économiser?)',
      analyzing: 'Réflexion...',
      error: 'Impossible d\'obtenir un conseil.',
      apiError: 'Erreur d\'analyse. Réessayez plus tard.',
      missingKey: 'Clé API manquante.'
    },
    settings: {
      title: 'Paramètres',
      generalTab: 'Général',
      categoriesTab: 'Catégories',
      appearance: 'Apparence',
      darkMode: 'Mode Sombre',
      sound: 'Sons',
      language: 'Langue',
      currency: 'Devise',
      selectCurrency: 'Choisir Devise',
      incomeTab: 'Revenu',
      expenseTab: 'Dépense',
      savingsTab: 'Épargne',
      placeholder: 'Nouvelle catégorie...',
      add: 'Ajouter',
      close: 'Fermer',
      exists: 'La catégorie existe déjà.',
      deleteTitle: 'Supprimer Catégorie',
      deleteConfirm: 'Supprimer cette catégorie?',
      dataManagement: 'Gestion des Données',
      backupTitle: 'Sauvegarde',
      backupDesc: 'Sauvegarder ou transférer les données.',
      backupEmail: 'Sauvegarde par Email',
      restoreData: 'Restaurer',
      clearData: 'Réinitialiser',
      clearDataDesc: 'Supprimer toutes les transactions.',
      confirmClearTitle: 'Réinitialiser?',
      confirmClearDesc: 'Ceci supprimera toutes les entrées.',
      confirmRestoreTitle: 'Restaurer?',
      confirmRestoreDesc: 'Ceci remplacera les données actuelles.',
      successRestore: 'Données restaurées!',
      errorRestore: 'Fichier invalide.',
      shareExport: 'Partager et Exporter',
      openShare: 'Options de Partage',
      logout: 'Déconnexion',
      logoutConfirm: 'Voulez-vous vraiment vous déconnecter?'
    },
    profile: {
      title: 'Gestionnaire de Profil',
      create: 'Créer Profil',
      switch: 'Changer',
      edit: 'Modifier',
      update: 'Mettre à jour',
      delete: 'Supprimer',
      namePlaceholder: 'Nom du Profil',
      deleteTitle: 'Supprimer Profil',
      confirmDelete: 'Sûr? Les données seront perdues.',
      active: 'Actif',
      cantDeleteLast: 'Impossible de supprimer le dernier profil.'
    },
    share: {
      title: 'Partager',
      desc: 'Exportez ou partagez vos données.',
      exportCsv: 'Exporter CSV',
      copySummary: 'Copier Résumé',
      csvDesc: 'Télécharger en tableur.',
      summaryDesc: 'Copier le rapport.',
      copied: 'Copié!',
      totalBalance: 'Solde Total',
      netIncome: 'Revenu Net',
      netExpense: 'Dépense Nette',
      totalSavings: 'Épargne Totale',
      exportPdf: 'Exporter PDF',
      pdfDesc: 'Télécharger rapport détaillé.',
      sharePdf: 'Partager PDF',
      sharePdfDesc: 'Envoyer par Email ou WhatsApp.',
      shareWhatsapp: 'WhatsApp',
      shareWhatsappDesc: 'Envoyer résumé par WhatsApp.',
      shareMail: 'Email',
      shareMailDesc: 'Envoyer résumé par Email.'
    },
    calculator: {
      title: 'Calculatrice',
      copy: 'Copier',
      copied: 'Copié!',
      clear: 'AC',
      error: 'Erreur'
    },
    common: {
      soundOn: 'Son On',
      soundOff: 'Son Off',
      on: 'On',
      off: 'Off',
      confirm: 'Confirmer',
      cancel: 'Annuler',
      note: 'Note'
    }
};

const HI_TRANSLATIONS = {
    dashboard: {
      balance: 'वर्तमान शेष',
      income: 'कुल आय',
      expense: 'कुल व्यय',
      savings: 'कुल बचत',
    },
    form: {
      title: 'लेन-देन जोड़ें',
      editTitle: 'लेन-देन संपादित करें',
      income: 'आय',
      expense: 'व्यय',
      savings: 'बचत',
      amount: 'राशि',
      category: 'श्रेणी',
      date: 'तारीख',
      note: 'नोट (वैकल्पिक)',
      addBtn: 'जोड़ें',
      updateBtn: 'अपडेट करें',
      cancelBtn: 'रद्द करें',
      placeholderAmount: '0.00',
      placeholderNote: 'उदा. खरीदारी',
      alertAmount: 'कृपया एक मान्य राशि दर्ज करें।',
      alertCategory: 'कृपया एक श्रेणी चुनें।',
      deductFromBalance: 'शेष राशि से काटें?',
      deductDesc: 'पैसे वर्तमान शेष से घटाए जाएंगे।',
      noDeductDesc: 'केवल बचत में जोड़ता है। शेष राशि अपरिवर्तित रहती है।',
    },
    list: {
      title: 'हाल का इतिहास',
      emptyTitle: 'कोई लेन-देन नहीं',
      emptyDesc: 'ट्रैकिंग शुरू करने के लिए अपनी पहली आय या व्यय जोड़ें।',
      deleteTitle: 'हटाएं',
      deleteConfirm: 'क्या आप वाकई इसे हटाना चाहते हैं?',
      confirm: 'पुष्टि करें',
      cancel: 'रद्द करें'
    },
    chart: {
      title: 'श्रेणी के अनुसार व्यय',
      empty: 'व्यय विवरण देखने के लिए खर्च जोड़ें।',
      tooltipAmount: 'राशि'
    },
    goals: {
      title: 'फंड और बचत',
      empty: 'कोई बचत लक्ष्य नहीं।',
      saved: 'जमा',
      target: 'लक्ष्य',
      completed: 'पूरा हुआ!',
      addMoney: 'जमा करें',
      create: 'नया फंड',
      edit: 'संपादित करें',
      update: 'अपडेट',
      name: 'फंड का नाम',
      placeholderName: 'उदा. नया लैपटॉप',
      deleteConfirm: 'क्या आप इस फंड को हटाना चाहते हैं?',
      depositTitle: 'जमा करें',
      depositBtn: 'जमा करें',
      withdrawBtn: 'निकालें',
      withdrawTitle: 'फंड से निकालें',
      isFixedDeposit: 'फिक्स्ड डिपॉजिट (FD) के रूप में चिह्नित करें',
      fdDesc: 'पैसा लॉक रहेगा। तोड़ने के लिए पुष्टि की आवश्यकता है।',
      breakFdTitle: 'FD तोड़ें?',
      breakFdConfirm: 'क्या आप वाकई समय से पहले यह FD तोड़ना चाहते हैं?',
      confirmWithdraw: 'मुख्य शेष राशि में वापस लें?',
      fixedDeposit: 'फिक्स्ड डिपॉजिट',
      category: 'बचत श्रेणी'
    },
    funds: {
      title: 'फंड',
      emptyGoals: 'कोई फंड नहीं।',
      saved: 'जमा',
      target: 'लक्ष्य',
      addMoney: 'पैसे जोड़ें',
      addGoal: 'लक्ष्य जोड़ें',
      editGoal: 'लक्ष्य संपादित करें',
      create: 'बनाएं',
      update: 'अपडेट',
      goalName: 'नाम',
      deposit: 'जमा',
      deleteGoalConfirm: 'लक्ष्य हटाएं?'
    },
    ai: {
      title: 'AI वित्तीय सुझाव',
      desc: 'Gemini AI से अपने खर्चों के बारे में पूछें।',
      btn: 'सुझाव प्राप्त करें',
      askBtn: 'AI से पूछें',
      placeholder: 'एक प्रश्न पूछें (उदा. और कैसे बचाएं?)',
      analyzing: 'सोच रहा हूँ...',
      error: 'सुझाव प्राप्त नहीं कर सका।',
      apiError: 'डेटा विश्लेषण में त्रुटि। कृपया बाद में प्रयास करें।',
      missingKey: 'API कुंजी गायब है।'
    },
    settings: {
      title: 'सेटिंग्स',
      generalTab: 'सामान्य',
      categoriesTab: 'श्रेणियाँ',
      appearance: 'दिखावट',
      darkMode: 'डार्क मोड',
      sound: 'ध्वनि प्रभाव',
      language: 'भाषा',
      currency: 'मुद्रा',
      selectCurrency: 'मुद्रा चुनें',
      incomeTab: 'आय',
      expenseTab: 'व्यय',
      savingsTab: 'बचत',
      placeholder: 'नई श्रेणी का नाम...',
      add: 'जोड़ें',
      close: 'बंद करें',
      exists: 'श्रेणी पहले से मौजूद है।',
      deleteTitle: 'श्रेणी हटाएं',
      deleteConfirm: 'क्या आप इस श्रेणी को हटाना चाहते हैं?',
      dataManagement: 'डेटा प्रबंधन',
      backupTitle: 'बैकअप और रिस्टोर',
      backupDesc: 'डेटा सहेजें या स्थानांतरित करें।',
      backupEmail: 'ईमेल बैकअप',
      restoreData: 'डेटा रिस्टोर करें',
      clearData: 'रीसेट करें',
      clearDataDesc: 'सभी लेन-देन हटाएं।',
      confirmClearTitle: 'रीसेट करें?',
      confirmClearDesc: 'यह सभी प्रविष्टियों को हटा देगा। सेटिंग्स सुरक्षित रहेंगी।',
      confirmRestoreTitle: 'रिस्टोर करें?',
      confirmRestoreDesc: 'यह वर्तमान डेटा को बदल देगा।',
      successRestore: 'डेटा रिस्टोर किया गया!',
      errorRestore: 'अमान्य फ़ाइल।',
      shareExport: 'साझा और निर्यात',
      openShare: 'साझा विकल्प',
      logout: 'लॉग आउट',
      logoutConfirm: 'क्या आप वाकई लॉग आउट करना चाहते हैं?'
    },
    profile: {
      title: 'प्रोफ़ाइल प्रबंधक',
      create: 'प्रोफ़ाइल बनाएं',
      switch: 'बदलें',
      edit: 'संपादित करें',
      update: 'अपडेट',
      delete: 'हटाएं',
      namePlaceholder: 'प्रोफ़ाइल का नाम',
      deleteTitle: 'प्रोफ़ाइल हटाएं',
      confirmDelete: 'पक्का? डेटा खो जाएगा।',
      active: 'सक्रिय',
      cantDeleteLast: 'अंतिम प्रोफ़ाइल नहीं हटा सकते।'
    },
    share: {
      title: 'साझा करें',
      desc: 'अपना डेटा निर्यात या साझा करें।',
      exportCsv: 'CSV निर्यात',
      copySummary: 'सारांश कॉपी करें',
      csvDesc: 'स्प्रेडशीट के रूप में डाउनलोड करें।',
      summaryDesc: 'रिपोर्ट क्लिपबोर्ड पर कॉपी करें।',
      copied: 'कॉपी किया गया!',
      totalBalance: 'कुल शेष',
      netIncome: 'शुद्ध आय',
      netExpense: 'शुद्ध व्यय',
      totalSavings: 'कुल बचत',
      exportPdf: 'PDF निर्यात',
      pdfDesc: 'विस्तृत रिपोर्ट डाउनलोड करें।',
      sharePdf: 'PDF साझा करें',
      sharePdfDesc: 'ईमेल या व्हाट्सएप द्वारा भेजें।',
      shareWhatsapp: 'व्हाट्सएप',
      shareWhatsappDesc: 'व्हाट्सएप पर सारांश भेजें।',
      shareMail: 'ईमेल',
      shareMailDesc: 'ईमेल पर सारांश भेजें।'
    },
    calculator: {
      title: 'कैलकुलेटर',
      copy: 'कॉपी',
      copied: 'कॉपी!',
      clear: 'AC',
      error: 'त्रुटि'
    },
    common: {
      soundOn: 'ध्वनि चालू',
      soundOff: 'ध्वनि बंद',
      on: 'चालू',
      off: 'बंद',
      confirm: 'पुष्टि करें',
      cancel: 'रद्द करें',
      note: 'नोट'
    }
};

const JA_TRANSLATIONS = {
    dashboard: {
      balance: '現在の残高',
      income: '総収入',
      expense: '総支出',
      savings: '総貯蓄',
    },
    form: {
      title: '取引を追加',
      editTitle: '取引を編集',
      income: '収入',
      expense: '支出',
      savings: '貯蓄',
      amount: '金額',
      category: 'カテゴリ',
      date: '日付',
      note: 'メモ (任意)',
      addBtn: '追加',
      updateBtn: '更新',
      cancelBtn: 'キャンセル',
      placeholderAmount: '0.00',
      placeholderNote: '例: 食料品',
      alertAmount: '有効な金額を入力してください。',
      alertCategory: 'カテゴリを選択してください。',
      deductFromBalance: '残高から差し引く？',
      deductDesc: '現在のお金から金額が引かれます。',
      noDeductDesc: '貯蓄に追加するだけです。残高は変わりません。',
    },
    list: {
      title: '最近の履歴',
      emptyTitle: '取引なし',
      emptyDesc: '最初の収入や支出を追加してください。',
      deleteTitle: '削除',
      deleteConfirm: '本当に削除しますか？',
      confirm: '確認',
      cancel: 'キャンセル'
    },
    chart: {
      title: 'カテゴリ別の支出',
      empty: '支出を追加して詳細を表示します。',
      tooltipAmount: '金額'
    },
    goals: {
      title: '資金と貯蓄',
      empty: '貯蓄目標はありません。',
      saved: '保存済み',
      target: '目標',
      completed: '完了！',
      addMoney: '預金',
      create: '新規ファンド',
      edit: '編集',
      update: '更新',
      name: 'ファンド名',
      placeholderName: '例: 新しいPC',
      deleteConfirm: 'このファンドを削除しますか？',
      depositTitle: '預金',
      depositBtn: '預金',
      withdrawBtn: '引き出す',
      withdrawTitle: 'ファンドから引き出す',
      isFixedDeposit: '定期預金 (FD) としてマーク',
      fdDesc: '資金はロックされます。解約には確認が必要です。',
      breakFdTitle: '定期預金を解約？',
      breakFdConfirm: '本当に早期解約しますか？',
      confirmWithdraw: 'メイン残高に戻しますか？',
      fixedDeposit: '定期預金',
      category: '貯蓄カテゴリ'
    },
    funds: {
      title: 'ファンド',
      emptyGoals: 'ファンドなし。',
      saved: '保存済み',
      target: '目標',
      addMoney: '追加',
      addGoal: '目標追加',
      editGoal: '編集',
      create: '作成',
      update: '更新',
      goalName: '名前',
      deposit: '預金',
      deleteGoalConfirm: '削除しますか？'
    },
    ai: {
      title: 'AI 金融インサイト',
      desc: 'Gemini AI に支出について質問します。',
      btn: 'ヒントを生成',
      askBtn: 'AIに聞く',
      placeholder: '質問を入力 (例: もっと節約するには？)',
      analyzing: '考え中...',
      error: 'ヒントを取得できませんでした。',
      apiError: '分析エラー。後でもう一度お試しください。',
      missingKey: 'APIキーがありません。'
    },
    settings: {
      title: '設定',
      generalTab: '一般',
      categoriesTab: 'カテゴリ',
      appearance: '外観',
      darkMode: 'ダークモード',
      sound: '効果音',
      language: '言語',
      currency: '通貨',
      selectCurrency: '通貨を選択',
      incomeTab: '収入',
      expenseTab: '支出',
      savingsTab: '貯蓄',
      placeholder: '新しいカテゴリ名...',
      add: '追加',
      close: '閉じる',
      exists: 'カテゴリは既に存在します。',
      deleteTitle: 'カテゴリ削除',
      deleteConfirm: 'このカテゴリを削除しますか？',
      dataManagement: 'データ管理',
      backupTitle: 'バックアップと復元',
      backupDesc: 'データを保存または転送します。',
      backupEmail: 'メールバックアップ',
      restoreData: '復元',
      clearData: 'リセット',
      clearDataDesc: 'すべての取引を削除します。',
      confirmClearTitle: 'リセットしますか？',
      confirmClearDesc: 'すべてのエントリが削除されます。設定は保持されます。',
      confirmRestoreTitle: '復元しますか？',
      confirmRestoreDesc: '現在のデータが置き換えられます。',
      successRestore: 'データが復元されました！',
      errorRestore: '無効なファイル。',
      shareExport: '共有とエクスポート',
      openShare: '共有オプション',
      logout: 'ログアウト',
      logoutConfirm: '本当にログアウトしますか？'
    },
    profile: {
      title: 'プロファイル管理',
      create: '作成',
      switch: '切り替え',
      edit: '編集',
      update: '更新',
      delete: '削除',
      namePlaceholder: 'プロファイル名',
      deleteTitle: '削除',
      confirmDelete: '本当ですか？データは失われます。',
      active: 'アクティブ',
      cantDeleteLast: '最後のプロファイルは削除できません。'
    },
    share: {
      title: '共有',
      desc: 'データをエクスポートまたは共有します。',
      exportCsv: 'CSV エクスポート',
      copySummary: '概要をコピー',
      csvDesc: 'スプレッドシートとしてダウンロード。',
      summaryDesc: 'レポートをクリップボードにコピー。',
      copied: 'コピーしました！',
      totalBalance: '総残高',
      netIncome: '純収入',
      netExpense: '純支出',
      totalSavings: '総貯蓄',
      exportPdf: 'PDF エクスポート',
      pdfDesc: '詳細レポートをダウンロード。',
      sharePdf: 'PDF 共有',
      sharePdfDesc: 'メールまたはWhatsAppで送信。',
      shareWhatsapp: 'WhatsApp',
      shareWhatsappDesc: 'WhatsAppで概要を送信。',
      shareMail: 'メール',
      shareMailDesc: 'メールで概要を送信。'
    },
    calculator: {
      title: '電卓',
      copy: 'コピー',
      copied: 'コピー！',
      clear: 'AC',
      error: 'エラー'
    },
    common: {
      soundOn: '音オン',
      soundOff: '音オフ',
      on: 'オン',
      off: 'オフ',
      confirm: '確認',
      cancel: 'キャンセル',
      note: 'メモ'
    }
};

export const TRANSLATIONS = {
  en: EN_TRANSLATIONS,
  bn: BN_TRANSLATIONS,
  hi: HI_TRANSLATIONS,
  fr: FR_TRANSLATIONS,
  es: ES_TRANSLATIONS,
  de: DE_TRANSLATIONS,
  ja: JA_TRANSLATIONS,
};
