import React, { useState } from 'react';
import { Transaction, DashboardStats, TRANSLATIONS, Language, convertAmount, TransactionType, getLocalizedCategory } from '../types';
import { X, Share2, FileSpreadsheet, Copy, CheckCircle2, FileText, Mail, MessageCircle } from 'lucide-react';
import { jsPDF } from "jspdf";
import { playSound } from '../utils/sound';
import { safeCopy } from '../utils/clipboard';

interface Props {
  isOpen: boolean;
  onClose: () => void;
  transactions: Transaction[];
  stats: DashboardStats;
  profileName: string;
  currency: string;
  language: Language;
  soundEnabled: boolean;
}

export const ShareModal: React.FC<Props> = ({
  isOpen,
  onClose,
  transactions,
  stats,
  profileName,
  currency,
  language,
  soundEnabled
}) => {
  const [copied, setCopied] = useState(false);
  const t = TRANSLATIONS[language].share;

  if (!isOpen) return null;

  const playClick = () => {
    if (soundEnabled) playSound('click');
  };

  const handleClose = () => {
    playClick();
    onClose();
  };

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat(language === 'bn' ? 'bn-BD' : 'en-US', {
      style: 'currency',
      currency: currency,
    }).format(amount);
  };

  const getExpenseBreakdown = () => {
    // 1. Group expenses by category
    const categoryMap = new Map<string, number>();
    
    transactions
        .filter(t => t.type === TransactionType.EXPENSE)
        .forEach(t => {
            const convertedVal = convertAmount(t.amount, t.currency || 'USD', currency);
            const catName = getLocalizedCategory(t.category, language);
            const currentVal = categoryMap.get(catName) || 0;
            categoryMap.set(catName, currentVal + convertedVal);
        });

    // 2. Sort by amount (descending)
    const sortedCategories = Array.from(categoryMap.entries())
        .sort((a, b) => b[1] - a[1]);

    // 3. Format as text string
    if (sortedCategories.length === 0) return "";

    const title = language === 'bn' ? 'খরচের বিবরণ:' : 'Expense Breakdown:';
    const lines = sortedCategories.map(([cat, amount]) => {
        return `• ${cat}: ${formatCurrency(amount)}`;
    });

    return `\n${title}\n${lines.join('\n')}`;
  };

  const getSummaryText = () => {
    const breakdown = getExpenseBreakdown();
    
    return `
📊 *Hisab Report* (${profileName})
---------------------------
💰 ${t.totalBalance}: ${formatCurrency(stats.balance)}
📈 ${t.netIncome}: ${formatCurrency(stats.totalIncome)}
📉 ${t.netExpense}: ${formatCurrency(stats.totalExpense)}
---------------------------
${breakdown}

Generated by Hisab
    `.trim();
  };

  const generatePDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    
    // Header
    doc.setFontSize(22);
    doc.setTextColor(22, 163, 74); // Green-600
    doc.text("Hisab Report", 20, 20);
    
    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text(`Profile: ${profileName}`, 20, 30);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 36);

    // Summary Box Background
    doc.setDrawColor(226, 232, 240); // Slate-200
    doc.setFillColor(248, 250, 252); // Slate-50
    doc.rect(20, 45, pageWidth - 40, 45, 'FD');

    // Summary Title
    doc.setFontSize(14);
    doc.setTextColor(30);
    doc.text(t.title === 'Share & Export' ? 'Financial Summary' : 'আর্থিক সারাংশ', 30, 60);

    // Summary Labels
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(t.totalBalance.toUpperCase(), 30, 72);
    doc.text(t.netIncome.toUpperCase(), 85, 72);
    doc.text(t.netExpense.toUpperCase(), 140, 72);

    // Summary Values
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    
    // Balance Value
    const balanceColor = stats.balance >= 0 ? [22, 163, 74] : [225, 29, 72];
    doc.setTextColor(balanceColor[0], balanceColor[1], balanceColor[2]);
    doc.text(formatCurrency(stats.balance), 30, 80);

    // Income Value
    doc.setTextColor(22, 163, 74); // Emerald
    doc.text(formatCurrency(stats.totalIncome), 85, 80);

    // Expense Value
    doc.setTextColor(225, 29, 72); // Rose
    doc.text(formatCurrency(stats.totalExpense), 140, 80);

    // Category Breakdown Section
    doc.setFont("helvetica", "normal");
    doc.setFontSize(14);
    doc.setTextColor(30);
    doc.text(language === 'en' ? "Top Expenses by Category" : "শীর্ষ ব্যয়ের খাতসমূহ", 20, 110);

    // Calculate Breakdown
    const expenseData = transactions
      .filter(t => t.type === TransactionType.EXPENSE)
      .reduce((acc, curr) => {
        const convertedAmount = convertAmount(curr.amount, curr.currency || 'USD', currency);
        // Use localized name here for PDF display
        const localCat = getLocalizedCategory(curr.category, language);
        const existing = acc.find(item => item.name === localCat);
        if (existing) {
          existing.value += convertedAmount;
        } else {
          acc.push({ name: localCat, value: convertedAmount });
        }
        return acc;
      }, [] as { name: string; value: number }[])
      .sort((a, b) => b.value - a.value)
      .slice(0, 8); // Top 8

    let yPos = 125;
    doc.setFontSize(11);
    doc.setTextColor(70);
    
    // Draw breakdown table-like structure
    if (expenseData.length > 0) {
        expenseData.forEach((item, index) => {
            const percent = stats.totalExpense > 0 ? ((item.value / stats.totalExpense) * 100).toFixed(1) : "0";
            
            // Background stripe for alternate rows
            if (index % 2 === 0) {
               doc.setFillColor(249, 250, 251);
               doc.rect(20, yPos - 5, pageWidth - 40, 8, 'F');
            }

            // Note: jsPDF default fonts might not support Bangla characters perfectly.
            // Ideally, one would load a custom font (like Noto Sans Bengali) for PDF generation.
            // For now, English fallback is safer if Bangla chars render as gibberish, 
            // but we will attempt to print the string.
            doc.text(`${index + 1}. ${item.name}`, 25, yPos);
            doc.text(`${formatCurrency(item.value)}`, 130, yPos);
            doc.text(`${percent}%`, 170, yPos);
            yPos += 10;
        });
    } else {
        doc.text(language === 'en' ? "No expense data available." : "কোনো ব্যয়ের তথ্য নেই।", 25, yPos);
    }
    
    // Footer
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text("Generated by Hisab", 20, 280);
    
    return doc;
  };

  const handleExportCSV = () => {
    playClick();
    // CSV Header
    const headers = ["Date", "Type", "Category", "Amount", "Original Currency", "Note"];
    
    // CSV Rows
    const rows = transactions.map(t => [
      t.date,
      t.type,
      // Localize category in CSV too? Usually better to keep raw data, but user asked for "everything Bangla"
      getLocalizedCategory(t.category, language),
      t.amount.toString(),
      t.currency,
      `"${t.note.replace(/"/g, '""')}"` // Escape quotes in note
    ]);

    const csvContent = [
      headers.join(","),
      ...rows.map(row => row.join(","))
    ].join("\n");

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `hisab_${profileName.toLowerCase()}_${new Date().toISOString().split('T')[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleExportPDF = () => {
    const doc = generatePDF();
    doc.save(`hisab_report_${profileName.toLowerCase()}.pdf`);
  };

  const handleSharePDF = async () => {
    playClick();
    const doc = generatePDF();
    const blob = doc.output('blob');
    const file = new File([blob], `hisab_report_${profileName}.pdf`, { type: 'application/pdf' });
    
    if (navigator.canShare && navigator.canShare({ files: [file] })) {
      try {
        await navigator.share({
          files: [file],
          title: 'Hisab Financial Report',
          text: `Here is the financial report for ${profileName}.`,
        });
      } catch (err) {
        console.error('Share failed or cancelled:', err);
      }
    } else {
      // Fallback
      handleExportPDF();
      alert(language === 'bn' 
        ? 'আপনার ডিভাইসটি সরাসরি ফাইল শেয়ার সমর্থন করে না। পিডিএফটি ডাউনলোড করা হয়েছে। আপনি এটি ম্যানুয়ালি জিমেইল বা হোয়াটসঅ্যাপে সংযুক্ত করতে পারেন।'
        : 'Your device doesn\'t support direct file sharing. The PDF has been downloaded. You can manually attach it to Gmail or WhatsApp.'
      );
    }
  };

  const handleCopySummary = async () => {
    await safeCopy(getSummaryText());
    if (soundEnabled) playSound('income');
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleWhatsappShare = () => {
    playClick();
    const text = encodeURIComponent(getSummaryText());
    window.open(`https://wa.me/?text=${text}`, '_blank');
  };

  const handleEmailShare = () => {
    playClick();
    const subject = encodeURIComponent(`Hisab Report: ${profileName}`);
    const body = encodeURIComponent(getSummaryText());
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  };

  return (
    <div className="fixed inset-0 z-[80] flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-slate-900/60 backdrop-blur-sm" onClick={handleClose} />
      
      <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-xl w-full max-w-md relative z-10 flex flex-col overflow-hidden animate-in zoom-in-95 duration-200 transition-colors max-h-[85vh]">
        <div className="p-5 border-b border-slate-100 dark:border-slate-700 flex items-center justify-between bg-slate-50/50 dark:bg-slate-700/50">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-indigo-100 dark:bg-indigo-900/30 text-indigo-600 dark:text-indigo-400 rounded-lg">
              <Share2 size={20} />
            </div>
            <div>
              <h3 className="text-lg font-bold text-slate-800 dark:text-white">{t.title}</h3>
              <p className="text-xs text-slate-500 dark:text-slate-400">{t.desc}</p>
            </div>
          </div>
          <button onClick={handleClose} className="p-2 hover:bg-slate-100 dark:hover:bg-slate-700 rounded-full text-slate-500 dark:text-slate-400 transition-colors">
            <X size={20} />
          </button>
        </div>

        <div className="p-6 overflow-y-auto space-y-4">
          
          {/* Share PDF File (Direct) */}
          <button 
            onClick={handleSharePDF}
            className="w-full flex items-center gap-4 p-4 rounded-xl bg-indigo-50 dark:bg-indigo-900/10 border border-indigo-200 dark:border-indigo-800 hover:bg-indigo-100 dark:hover:bg-indigo-900/30 transition-all group text-left"
          >
            <div className="w-10 h-10 rounded-full bg-indigo-200 dark:bg-indigo-800 text-indigo-700 dark:text-indigo-200 flex items-center justify-center group-hover:scale-110 transition-transform">
              <Share2 size={20} />
            </div>
            <div className="flex-1">
              <h4 className="font-semibold text-indigo-900 dark:text-indigo-100">{t.sharePdf}</h4>
              <p className="text-xs text-indigo-700/70 dark:text-indigo-300/70">{t.sharePdfDesc}</p>
            </div>
          </button>

          <div className="grid grid-cols-2 gap-3">
            {/* WhatsApp */}
            <button 
              onClick={handleWhatsappShare}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl border border-slate-200 dark:border-slate-700 hover:border-green-500 hover:bg-green-50 dark:hover:bg-green-900/20 transition-all"
            >
              <div className="w-8 h-8 rounded-full bg-green-100 dark:bg-green-900/30 text-green-600 dark:text-green-400 flex items-center justify-center">
                <MessageCircle size={18} />
              </div>
              <span className="text-sm font-medium text-slate-700 dark:text-slate-200">{t.shareWhatsapp}</span>
            </button>

            {/* Email */}
            <button 
              onClick={handleEmailShare}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl border border-slate-200 dark:border-slate-700 hover:border-blue-500 hover:bg-blue-50 dark:hover:bg-blue-900/20 transition-all"
            >
              <div className="w-8 h-8 rounded-full bg-blue-100 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400 flex items-center justify-center">
                <Mail size={18} />
              </div>
              <span className="text-sm font-medium text-slate-700 dark:text-slate-200">{t.shareMail}</span>
            </button>
          </div>

          <div className="h-px bg-slate-100 dark:bg-slate-700 my-2"></div>

          {/* Export PDF Download */}
          <button 
            onClick={() => { playClick(); handleExportPDF(); }}
            className="w-full flex items-center gap-4 p-3 rounded-xl border border-slate-200 dark:border-slate-700 hover:border-slate-400 dark:hover:border-slate-500 hover:bg-slate-50 dark:hover:bg-slate-700/50 transition-all group text-left"
          >
            <div className="w-8 h-8 rounded-full bg-red-100 dark:bg-red-900/30 text-red-600 dark:text-red-400 flex items-center justify-center">
              <FileText size={16} />
            </div>
            <div className="flex-1">
              <h4 className="font-medium text-sm text-slate-800 dark:text-slate-200">{t.exportPdf}</h4>
              <p className="text-[10px] text-slate-500 dark:text-slate-400">{t.pdfDesc}</p>
            </div>
          </button>

          {/* Export CSV Download */}
          <button 
            onClick={handleExportCSV}
            className="w-full flex items-center gap-4 p-3 rounded-xl border border-slate-200 dark:border-slate-700 hover:border-slate-400 dark:hover:border-slate-500 hover:bg-slate-50 dark:hover:bg-slate-700/50 transition-all group text-left"
          >
            <div className="w-8 h-8 rounded-full bg-emerald-100 dark:bg-emerald-900/30 text-emerald-600 dark:text-emerald-400 flex items-center justify-center">
              <FileSpreadsheet size={16} />
            </div>
            <div className="flex-1">
              <h4 className="font-medium text-sm text-slate-800 dark:text-slate-200">{t.exportCsv}</h4>
              <p className="text-[10px] text-slate-500 dark:text-slate-400">{t.csvDesc}</p>
            </div>
          </button>

          {/* Copy Summary */}
          <button 
            onClick={handleCopySummary}
            className="w-full flex items-center gap-4 p-3 rounded-xl border border-slate-200 dark:border-slate-700 hover:border-slate-400 dark:hover:border-slate-500 hover:bg-slate-50 dark:hover:bg-slate-700/50 transition-all group text-left"
          >
            <div className="w-8 h-8 rounded-full bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-300 flex items-center justify-center">
              {copied ? <CheckCircle2 size={16} /> : <Copy size={16} />}
            </div>
            <div className="flex-1">
              <h4 className="font-medium text-sm text-slate-800 dark:text-slate-200">
                {copied ? t.copied : t.copySummary}
              </h4>
              <p className="text-[10px] text-slate-500 dark:text-slate-400">{t.summaryDesc}</p>
            </div>
          </button>
        </div>

        <div className="p-3 bg-slate-50 dark:bg-slate-800/50 text-center text-[10px] text-slate-400 border-t border-slate-100 dark:border-slate-700">
          Hisab v1.1
        </div>
      </div>
    </div>
  );
};